import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

/**
 * Source contract for the decision-note affordance inside the decisions panel.
 *
 * Two properties here cannot be reached by a unit test, because they are about
 * which state setter a handler is *able* to call:
 *
 *  1. Generating, failing, or retrying never writes `personalNote`. Only
 *     `applyDraft` may, and only through the tested pure function.
 *  2. Applying a draft invalidates any existing preview, exactly as typing in
 *     the field does — so `Send it` cannot ride a preview of older content.
 *
 * The second is belt-and-braces: the server already refuses a stale send,
 * because the preview token is bound to a digest over the rendered messages and
 * the personal note is in them (pinned in the route contract test). This panel
 * rail is what stops the UI *offering* a send it knows will fail.
 *
 * Source assertions are CRLF-safe: no pattern below crosses a line break.
 */
const PANEL = "app/(app)/admin/operations/decisions-panel.tsx";
const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

/** Comment text stripped, so "this file says X" is asserted against code. */
const code = (path: string) =>
  read(path).replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/[^\r\n]*/g, "$1");

const panel = () => code(PANEL);

/** One handler's body, so a claim about it cannot be satisfied by another. */
function handler(name: string): string {
  const source = panel();
  const start = source.indexOf(`function ${name}(`);
  assert.ok(start > -1, `${name} must exist in the panel`);
  const rest = source.slice(start);
  // Up to the next top-level `  function ` / `  async function ` declaration.
  const end = rest.slice(1).search(/\n {2}(?:async )?function /);
  return end === -1 ? rest : rest.slice(0, end + 1);
}

test("the panel offers drafting beside the personal-note field", () => {
  const it = panel();
  assert.match(it, /Draft note from feedback/);
  assert.match(it, /onClick=\{draftNote\}/);
  assert.match(it, /"\/api\/assistant\/decision-note"/);
  assert.match(it, /abstractId: selectedId, includeFeedback/);
  // Beside the note, not somewhere else on the page: the button markup sits
  // after the textarea's own id and before the panel's send actions.
  assert.ok(it.indexOf("ops-decision-note") < it.indexOf("Draft note from feedback"));
  assert.ok(it.indexOf("Draft note from feedback") < it.indexOf("Preview email"));
});

test("the disclosure is TRUE, not merely reassuring", () => {
  const it = read(PANEL);
  // Named provider destination, and what is actually sent.
  assert.match(it, /to the configured AI provider/);
  assert.match(it, /reviewer comments above to the configured AI provider/);
  assert.match(it, /No reviewer comments\./);

  // All four categories are ENUMERATED, event name included. An earlier
  // version said "those four things" while listing only three of them.
  assert.match(it, /the event name, the proposal title, your decision, and comment excerpts/);
  assert.match(it, /the event name, the proposal title, and your decision/);
  assert.match(it, /Sends the event name, the proposal title, your decision, and excerpts/);

  // The precise, true claim: no identity or score FIELD is looked up or added,
  // and no identifier is sent at all now that neither one is selected.
  assert.match(it, /No speaker or reviewer name, email address, score, or ID is looked up or added as a/);
  assert.match(it, /separate field, and no proposal or event ID is sent/);

  // The comment sentence is built from the real bounds rather than written out
  // here, so the numbers an organizer reads cannot drift from the projection.
  assert.match(it, /describeCommentDisclosure\(\)/);
  assert.match(it, /No comment text leaves this deployment while that box is unchecked/);

  // Neither overclaim may come back. "Never sent" was false the moment a
  // reviewer typed a name into an included comment; "word for word" was false
  // in the other direction, because the projection normalizes and truncates.
  assert.doesNotMatch(it, /are never sent/);
  assert.doesNotMatch(it, /are never included/);
  assert.doesNotMatch(it, /word for word/);

  // The include-feedback choice is stated to govern the draft too, so one
  // checkbox cannot silently mean two different things.
  assert.match(it, /whether that comment text is sent to the AI provider/);
  // And the suggestion is labelled as generated wherever it renders.
  assert.match(it, /Suggested draft/);
  assert.match(it, /Generated by AI/);
});

test("generating, failing, or retrying can never write the organizer's note", () => {
  // The whole no-overwrite guarantee in one assertion: the request handler does
  // not contain the note's setter at all, so no failure path inside it can
  // reach the field.
  const draft = handler("draftNote");
  assert.doesNotMatch(draft, /setPersonalNote/, "draftNote must not be able to touch the note");
  // Every state write in the handler sits behind the freshness gate, so a slow
  // response for one proposal cannot install under another.
  assert.match(draft, /const token = \{ seq: draftSeq\.current, abstractId: selectedId, includeFeedback \};/);
  assert.match(draft, /if \(!isDraftResponseCurrent\(token, current\(\)\)\) return;/);
  assert.match(draft, /if \(isDraftResponseCurrent\(token, current\(\)\)\) setDraftError\(/);
  assert.ok(
    draft.indexOf("isDraftResponseCurrent") < draft.indexOf("setSuggestion("),
    "the freshness gate must precede the only call that installs a suggestion",
  );
  // The counter is bumped by the one function every invalidating change calls.
  assert.match(handler("clearSuggestion"), /draftSeq\.current \+= 1;/);
  assert.equal(
    (panel().match(/setSuggestion\(\{/g) ?? []).length,
    1,
    "exactly one place installs a suggestion, and it is the gated one",
  );
  assert.match(draft, /setDraftError\(describeDraftFailure\(/);
  assert.match(draft, /setSuggestion\(\{/);
  // A failed request must not log: the response body sits next to a prompt.
  assert.doesNotMatch(draft, /console\./);

  // Exactly two writers of the note in the whole panel: the textarea's own
  // onChange, and applyDraft.
  const writes = (panel().match(/setPersonalNote\(/g) ?? []).length;
  assert.equal(writes, 2, "only the textarea and applyDraft may set the note");
  assert.match(panel(), /onChange=\{\(e\) => \{ setPersonalNote\(e\.target\.value\); setPreview\(null\); \}\}/);
});

test("applying goes through the tested pure function, and confirms before replacing", () => {
  const apply = handler("applyDraft");
  assert.match(apply, /applyDraftToNote\(\{ note: personalNote, draft: suggestion\.draft, confirmed \}\)/);
  // The panel does not re-derive the rule; it obeys the outcome.
  assert.match(apply, /if \(outcome\.status === "needs-confirmation"\) \{/);
  assert.match(apply, /setConfirmReplace\(true\);/);
  assert.match(apply, /if \(outcome\.status === "empty"\) return;/);
  assert.match(apply, /setPersonalNote\(outcome\.note\);/);
  // It writes the function's note, never the raw draft — otherwise the empty
  // and needs-confirmation branches could be bypassed.
  assert.doesNotMatch(apply, /setPersonalNote\(suggestion\.draft\)/);
  assert.doesNotMatch(apply, /setPersonalNote\(draft\)/);

  // The confirmation is a real second click on a differently-worded control.
  const markup = read(PANEL);
  assert.match(markup, /Yes, replace my note/);
  assert.match(markup, /Keep what I wrote/);
  assert.match(markup, /replace the note you have already written/);
  assert.match(markup, /onClick=\{\(\) => applyDraft\(true\)\}/);
  assert.match(markup, /onClick=\{\(\) => applyDraft\(false\)\}/);
  // And discarding is one click that touches no note.
  assert.match(markup, /onClick=\{clearSuggestion\}/);
  assert.doesNotMatch(handler("clearSuggestion"), /setPersonalNote|setPreview/);
});

test("applying invalidates the preview, on the same rule typing already followed", () => {
  const apply = handler("applyDraft");
  assert.match(apply, /setPreview\(null\);/, "an applied draft must invalidate any prior preview");
  // Ordering: the note is written, then the preview is dropped, so no render
  // between them can observe a preview that matches the old note.
  assert.ok(
    apply.indexOf("setPersonalNote(outcome.note)") < apply.indexOf("setPreview(null)"),
    "the preview must be cleared after the note changes",
  );

  // Every other content change still clears it too — the panel's existing
  // mechanism, which this feature reuses rather than replaces.
  const it = panel();
  assert.match(it, /setSelectedId\(e\.target\.value\); setPreview\(null\)/);
  assert.match(it, /setIncludeFeedback\(e\.target\.checked\); setPreview\(null\)/);
  // And `Send it` is still gated on a live preview object.
  assert.match(it, /disabled=\{busy \|\| !preview\}/);
  assert.match(it, /\{!preview \? <span className="muted">Preview first<\/span> : null\}/);
  // The rendered email is a named region. It is what a screen reader lands on
  // rather than loose text, and it is what the browser proof asserts against —
  // without it, "the preview contains the note" also matches the textarea that
  // produced the note, and the assertion proves nothing.
  assert.match(read(PANEL), /role="group" aria-label="Email preview"/);
});

test("the send path itself is unchanged: same body, same token, same server gate", () => {
  const it = panel();
  // Untouched from before the feature: the preview token round-trip is what the
  // server verifies against a digest of the exact rendered content.
  assert.match(it, /previewToken: previewOnly \? undefined : preview\?\.previewToken,/);
  assert.match(it, /personalNote: personalNote\.trim\(\) \? personalNote : null,/);
  assert.match(it, /"\/api\/comms\/decision"/);
  // The drafting request is a separate call that cannot send anything.
  assert.doesNotMatch(handler("draftNote"), /\/api\/comms\/decision|previewToken|preview: /);
});

test("the drafting states are announced and cannot be double-fired", () => {
  const it = read(PANEL);
  assert.match(it, /aria-busy=\{drafting\}/);
  assert.match(it, /role="status" aria-live="polite"/);
  assert.match(it, /disabled=\{busy \|\| drafting \|\| !selectedId\}/, "duplicate generation must be refused");
  assert.match(it, /\{drafting \? "Drafting…" : "Draft note from feedback"\}/);
  assert.match(it, /Drafting unavailable/);
  // Manual composition stays available throughout: the textarea is disabled by
  // a send in flight, never by drafting.
  assert.match(it, /id="ops-decision-note" rows=\{3\} value=\{personalNote\} disabled=\{busy\}/);
});

test("the panel reaches the server-only assistant only over HTTP", () => {
  const it = read(PANEL);
  assert.match(it, /^"use client";/);
  // The pure logic it imports lives outside lib/assistant on purpose; the
  // transitive rail in lib/assistant/client.test.ts is what enforces the rest.
  assert.match(it, /from "@\/lib\/decision-note-ui"/);
  assert.doesNotMatch(it, /@\/lib\/assistant/);
  assert.doesNotMatch(it, /@\/lib\/prisma|@\/lib\/env|process\.env/);
});
