"use client";

import { useState } from "react";
import { Mails, Send } from "lucide-react";
import styles from "./operations.module.css";

type DecidedAbstract = {
  id: string;
  title: string;
  status: "ACCEPTED" | "REJECTED";
  speakerName: string;
  recipientCount: number;
  feedbackCount: number;
};

type Preview = {
  subject: string;
  html: string;
  recipients: string[];
  feedbackCount: number;
  willSend: boolean;
};

type Result = { tone: "good" | "warn" | "bad"; headline: string; note?: string };

/**
 * Email a speaker their decision, optionally with the review team's written
 * feedback (the director's explicit bonus).
 *
 * Preview is mandatory before sending: this is the email a speaker reads at
 * their most invested, and an operator should never fire it blind. The preview
 * is generated by the same server code that would send it, not a client-side
 * approximation, so what is shown is exactly what goes out.
 */
export function DecisionsPanel({ decided }: { decided: DecidedAbstract[] }) {
  const [selectedId, setSelectedId] = useState(decided[0]?.id ?? "");
  const [includeFeedback, setIncludeFeedback] = useState(true);
  const [personalNote, setPersonalNote] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<Result | null>(null);

  const selected = decided.find((item) => item.id === selectedId) ?? null;

  async function call(previewOnly: boolean) {
    setBusy(true);
    setResult(null);
    try {
      const res = await fetch("/api/comms/decision", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          abstractId: selectedId,
          preview: previewOnly,
          includeFeedback,
          personalNote: personalNote.trim() ? personalNote : null,
        }),
      });
      const body = await res.json();
      if (!body?.ok) {
        setResult({ tone: "bad", headline: body?.error?.message ?? "That could not be prepared." });
        return;
      }
      if (previewOnly) {
        setPreview(body.data as Preview);
        return;
      }
      const { sent, mocked, failed, recipients } = body.data;
      setResult(
        failed > 0
          ? { tone: "warn", headline: `${sent + mocked} of ${recipients.length} emails went out; ${failed} failed.`, note: "Failed sends are recorded — check the mail provider and try again." }
          : mocked > 0
            ? { tone: "warn", headline: `Demo mode: ${mocked} email${mocked === 1 ? "" : "s"} recorded but not delivered.`, note: "Connect a mail provider for this deployment to send for real." }
            : { tone: "good", headline: `Sent to ${recipients.join(", ")}.` },
      );
      setPreview(null);
    } catch {
      setResult({ tone: "bad", headline: "We couldn't reach the server. Check your connection and try again." });
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className={styles.panel} aria-labelledby="ops-decisions">
      <div className={styles.panelHead}>
        <h2 id="ops-decisions">Tell a speaker your decision</h2>
        <p>Send the outcome by email, with the review team&apos;s feedback if you want to share it.</p>
      </div>

      {decided.length === 0 ? (
        <p className={styles.empty}>No proposals have been accepted or declined yet.</p>
      ) : (
        <>
          <div className={styles.field}>
            <label className="field-label" htmlFor="ops-decision-abstract">Proposal</label>
            <select
              className="text-input" id="ops-decision-abstract" value={selectedId} disabled={busy}
              onChange={(e) => { setSelectedId(e.target.value); setPreview(null); setResult(null); }}
            >
              {decided.map((item) => (
                <option key={item.id} value={item.id}>
                  {item.status === "ACCEPTED" ? "Accepted" : "Declined"} · {item.title} · {item.speakerName}
                </option>
              ))}
            </select>
            {selected ? (
              <p className={styles.hintText}>
                Goes to {selected.recipientCount} recipient{selected.recipientCount === 1 ? "" : "s"} ·{" "}
                {selected.feedbackCount === 0
                  ? "no written reviewer feedback on this one"
                  : `${selected.feedbackCount} reviewer comment${selected.feedbackCount === 1 ? "" : "s"} available`}
              </p>
            ) : null}
          </div>

          <label className={styles.recipient}>
            <input
              type="checkbox" checked={includeFeedback} disabled={busy}
              onChange={(e) => { setIncludeFeedback(e.target.checked); setPreview(null); }}
            />
            Include the review team&apos;s comments
          </label>
          <p className={styles.hintText}>
            Comments only — scores and reviewer names are never included.
          </p>

          <div className={styles.field}>
            <label className="field-label" htmlFor="ops-decision-note">Add a personal note (optional)</label>
            <textarea
              className="text-input" id="ops-decision-note" rows={3} value={personalNote} disabled={busy}
              onChange={(e) => { setPersonalNote(e.target.value); setPreview(null); }}
            />
          </div>

          <div className={styles.actions}>
            <button className="ghost-button" type="button" onClick={() => call(true)} disabled={busy || !selectedId}>
              <Mails size={15} aria-hidden="true" /> {busy && !preview ? "Preparing…" : "Preview email"}
            </button>
            <button className="primary-button" type="button" onClick={() => call(false)} disabled={busy || !preview}>
              <Send size={15} aria-hidden="true" /> Send it
            </button>
            {!preview ? <span className="muted">Preview first</span> : null}
          </div>

          {preview ? (
            <div className={styles.field}>
              <span className="field-label">Exactly what they will receive</span>
              <p className={styles.hintText}>
                To: {preview.recipients.join(", ")}
                {preview.willSend ? "" : " · demo mode — this will be recorded, not delivered"}
              </p>
              <div className={styles.templatePreview}>
                <strong>{preview.subject}</strong>
                {/* Server-rendered from escaped/sanitized parts (lib/comms/notifications.ts). */}
                <div dangerouslySetInnerHTML={{ __html: preview.html }} />
              </div>
            </div>
          ) : null}
        </>
      )}

      {result ? (
        <div className={`${styles.result} ${result.tone === "good" ? styles.resultGood : result.tone === "bad" ? styles.resultBad : styles.resultWarn}`} role="status">
          <span className={styles.resultHead}>{result.headline}</span>
          {result.note ? <p className={styles.resultAdvice}>{result.note}</p> : null}
        </div>
      ) : null}
    </section>
  );
}
