"use client";

import { useState } from "react";
import { Mails, Send, Sparkles } from "lucide-react";
import {
  applyDraftToNote,
  describeApplyAction,
  describeDraftFailure,
  describeDraftGrounding,
  type DraftSuggestion,
} from "@/lib/decision-note-ui";
import styles from "./operations.module.css";

type DecidedAbstract = {
  id: string;
  title: string;
  status: "ACCEPTED" | "REJECTED";
  speakerName: string;
  recipientCount: number;
  feedbackCount: number;
};

type Preview = {
  subject: string;
  html: string;
  previewRecipient: string;
  recipients: string[];
  feedbackCount: number;
  willSend: boolean;
  previewToken: string;
};

type Result = { tone: "good" | "warn" | "bad"; headline: string; note?: string };

/**
 * Email a speaker their decision, optionally with the review team's written
 * feedback (the director's explicit bonus).
 *
 * Preview is mandatory before sending: this is the email a speaker reads at
 * their most invested, and an operator should never fire it blind. The preview
 * is generated by the same server code that would send it, not a client-side
 * approximation, so what is shown is exactly what goes out.
 */
export function DecisionsPanel({ decided }: { decided: DecidedAbstract[] }) {
  const [selectedId, setSelectedId] = useState(decided[0]?.id ?? "");
  const [includeFeedback, setIncludeFeedback] = useState(true);
  const [personalNote, setPersonalNote] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [suggestion, setSuggestion] = useState<DraftSuggestion | null>(null);
  const [drafting, setDrafting] = useState(false);
  const [draftError, setDraftError] = useState<string | null>(null);
  const [confirmReplace, setConfirmReplace] = useState(false);

  const selected = decided.find((item) => item.id === selectedId) ?? null;

  /** Drop a suggestion whose grounding no longer matches what is selected. */
  function clearSuggestion() {
    setSuggestion(null);
    setDraftError(null);
    setConfirmReplace(false);
  }

  /**
   * Ask for a draft. Nothing here writes to `personalNote`: a failure, a retry,
   * or a second generation leaves whatever the organizer has written exactly
   * where it was, and only `applyDraft` can change it.
   */
  async function draftNote() {
    setDrafting(true);
    clearSuggestion();
    try {
      const res = await fetch("/api/assistant/decision-note", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ abstractId: selectedId, includeFeedback }),
      });
      const body = await res.json();
      if (!body?.ok) {
        setDraftError(describeDraftFailure(body?.error?.message));
        return;
      }
      setSuggestion({
        draft: body.data.draft,
        commentsAvailable: body.data.grounding.commentsAvailable,
        commentIndexesUsed: body.data.grounding.commentIndexesUsed,
      });
    } catch {
      // Deliberately not logged: a failed draft request is not worth a console
      // entry that could carry the request or response near a prompt.
      setDraftError(describeDraftFailure(null));
    } finally {
      setDrafting(false);
    }
  }

  /**
   * Move a suggestion into the note. Over a non-empty note this needs a second,
   * explicit click — the panel never silently replaces organizer-authored text.
   * Applying invalidates any preview, exactly as typing in the field does.
   */
  function applyDraft(confirmed: boolean) {
    if (!suggestion) return;
    const outcome = applyDraftToNote({ note: personalNote, draft: suggestion.draft, confirmed });
    if (outcome.status === "needs-confirmation") {
      setConfirmReplace(true);
      return;
    }
    if (outcome.status === "empty") return;
    setPersonalNote(outcome.note);
    setPreview(null);
    clearSuggestion();
  }

  async function call(previewOnly: boolean) {
    setBusy(true);
    setResult(null);
    try {
      const res = await fetch("/api/comms/decision", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          abstractId: selectedId,
          preview: previewOnly,
          previewToken: previewOnly ? undefined : preview?.previewToken,
          includeFeedback,
          personalNote: personalNote.trim() ? personalNote : null,
        }),
      });
      const body = await res.json();
      if (!body?.ok) {
        setResult({ tone: "bad", headline: body?.error?.message ?? "That could not be prepared." });
        return;
      }
      if (previewOnly) {
        setPreview(body.data as Preview);
        return;
      }
      const { sent, mocked, failed, recipients } = body.data;
      setResult(
        failed > 0
          ? { tone: "warn", headline: `${sent + mocked} of ${recipients.length} emails went out; ${failed} failed.`, note: "Failed sends are recorded — check the mail provider and try again." }
          : mocked > 0
            ? { tone: "warn", headline: `Demo mode: ${mocked} email${mocked === 1 ? "" : "s"} recorded but not delivered.`, note: "Connect a mail provider for this deployment to send for real." }
            : { tone: "good", headline: `Sent to ${recipients.join(", ")}.` },
      );
      setPreview(null);
    } catch (error) {
      console.error("[comms] decision request failed", error);
      setResult({ tone: "bad", headline: "We couldn't reach the server. Check your connection and try again." });
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className={styles.panel} aria-labelledby="ops-decisions">
      <div className={styles.panelHead}>
        <h2 id="ops-decisions">Tell a speaker your decision</h2>
        <p>Send the outcome by email, with the review team&apos;s feedback if you want to share it.</p>
      </div>

      {decided.length === 0 ? (
        <p className={styles.empty}>No proposals have been accepted or declined yet.</p>
      ) : (
        <>
          <div className={styles.field}>
            <label className="field-label" htmlFor="ops-decision-abstract">Proposal</label>
            <select
              className="text-input" id="ops-decision-abstract" value={selectedId} disabled={busy}
              onChange={(e) => { setSelectedId(e.target.value); setPreview(null); setResult(null); clearSuggestion(); }}
            >
              {decided.map((item) => (
                <option key={item.id} value={item.id}>
                  {item.status === "ACCEPTED" ? "Accepted" : "Declined"} · {item.title} · {item.speakerName}
                </option>
              ))}
            </select>
            {selected ? (
              <p className={styles.hintText}>
                Goes to {selected.recipientCount} recipient{selected.recipientCount === 1 ? "" : "s"} ·{" "}
                {selected.feedbackCount === 0
                  ? "no written reviewer feedback on this one"
                  : `${selected.feedbackCount} reviewer comment${selected.feedbackCount === 1 ? "" : "s"} available`}
              </p>
            ) : null}
          </div>

          <label className={styles.recipient}>
            <input
              type="checkbox" checked={includeFeedback} disabled={busy}
              onChange={(e) => { setIncludeFeedback(e.target.checked); setPreview(null); clearSuggestion(); }}
            />
            Include the review team&apos;s comments
          </label>
          <p className={styles.hintText}>
            Comments only — scores and reviewer names are never included. This choice also
            decides whether those comments are sent to the AI provider when you ask for a draft below.
          </p>

          <div className={styles.field}>
            <label className="field-label" htmlFor="ops-decision-note">Add a personal note (optional)</label>
            <textarea
              className="text-input" id="ops-decision-note" rows={3} value={personalNote} disabled={busy}
              onChange={(e) => { setPersonalNote(e.target.value); setPreview(null); }}
            />
            <div className={styles.assistActions}>
              <button
                className="ghost-button" type="button" onClick={draftNote}
                disabled={busy || drafting || !selectedId} aria-busy={drafting}
              >
                <Sparkles size={15} aria-hidden="true" />
                {drafting ? "Drafting…" : "Draft note from feedback"}
              </button>
              <span className={styles.hintText}>
                {includeFeedback
                  ? "Sends the proposal title, your decision, and the reviewer comments above to the configured AI provider."
                  : "Sends the proposal title and your decision to the configured AI provider. No reviewer comments."}
              </span>
            </div>
            <p className={styles.hintText}>
              Speaker and reviewer names, email addresses, and scores are never sent. You always
              choose whether to use what comes back.
            </p>

            {/* One live region for the whole drafting interaction, so a screen
                reader hears the outcome without the panel announcing twice. */}
            <div role="status" aria-live="polite">
              {drafting ? <p className={styles.hintText}>Drafting a note…</p> : null}

              {draftError ? (
                <div className={`${styles.result} ${styles.resultWarn}`}>
                  <span className={styles.resultHead}>Drafting unavailable</span>
                  <p className={styles.resultAdvice}>{draftError}</p>
                </div>
              ) : null}

              {suggestion ? (
                <div className={styles.assist}>
                  <div className={styles.assistHead}>
                    <span className={styles.assistTag}>Suggested draft</span>
                    <span className={styles.hintText}>Generated by AI — read it before you use it.</span>
                  </div>
                  <p className={styles.assistDraft}>{suggestion.draft}</p>
                  <p className={styles.hintText}>{describeDraftGrounding(suggestion)}</p>
                  {confirmReplace ? (
                    <>
                      <p className={styles.hintText}>
                        This will replace the note you have already written. That cannot be undone.
                      </p>
                      <div className={styles.assistActions}>
                        <button className="primary-button" type="button" onClick={() => applyDraft(true)}>
                          Yes, replace my note
                        </button>
                        <button className="ghost-button" type="button" onClick={() => setConfirmReplace(false)}>
                          Keep what I wrote
                        </button>
                      </div>
                    </>
                  ) : (
                    <div className={styles.assistActions}>
                      <button className="ghost-button" type="button" onClick={() => applyDraft(false)}>
                        {describeApplyAction(personalNote)}
                      </button>
                      <button className="ghost-button" type="button" onClick={clearSuggestion}>
                        Discard
                      </button>
                    </div>
                  )}
                </div>
              ) : null}
            </div>
          </div>

          <div className={styles.actions}>
            <button className="ghost-button" type="button" onClick={() => call(true)} disabled={busy || !selectedId}>
              <Mails size={15} aria-hidden="true" /> {busy && !preview ? "Preparing…" : "Preview email"}
            </button>
            <button className="primary-button" type="button" onClick={() => call(false)} disabled={busy || !preview}>
              <Send size={15} aria-hidden="true" /> Send it
            </button>
            {!preview ? <span className="muted">Preview first</span> : null}
          </div>

          {preview ? (
            <div className={styles.field}>
              <span className="field-label">Preview for {preview.previewRecipient}</span>
              <p className={styles.hintText}>
                To: {preview.recipients.join(", ")}
                {preview.willSend ? "" : " · demo mode — this will be recorded, not delivered"}
              </p>
              {preview.recipients.length > 1 ? (
                <p className={styles.hintText}>Each recipient gets this message with their own greeting.</p>
              ) : null}
              {/* Named so the rendered email is one addressable region rather
                  than loose text beside the field that produced it. */}
              <div className={styles.templatePreview} role="group" aria-label="Email preview">
                <strong>{preview.subject}</strong>
                {/* Server-rendered from escaped/sanitized parts (lib/comms/notifications.ts). */}
                <div dangerouslySetInnerHTML={{ __html: preview.html }} />
              </div>
            </div>
          ) : null}
        </>
      )}

      {result ? (
        <div className={`${styles.result} ${result.tone === "good" ? styles.resultGood : result.tone === "bad" ? styles.resultBad : styles.resultWarn}`} role="status">
          <span className={styles.resultHead}>{result.headline}</span>
          {result.note ? <p className={styles.resultAdvice}>{result.note}</p> : null}
        </div>
      ) : null}
    </section>
  );
}
